# Generated by Django 5.1.6 on 2025-02-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(default='a.png', upload_to='upload')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('date_of_birth', models.CharField(max_length=10)),
            ],
        ),
    ]
